[tool.poetry]
name = "myproject"
version = "0.1.0"
description = "My project description"
authors = ["Your Name <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.9"
djangorestframework = ">=3.9.1"
py-spy = "^0.4.0"
pytz = "^2025.1"
django = ">=2.1.5"
flask = "^3.0.0"

